allpictures/urls.py
from django.contrib import admin
from django.urls import path
from allpictures import views

app_name = 'allpictures'
urlpatterns = [
    path('', views.picture_list, name='list'),
    path('my_picture', views.my_picture_list, name="my_picture_list"),
]

home/urls.py
from django.contrib import admin
from django.urls import path, include

from home import views
from home.views import PostList, PostDetail, PostListByCategory, PostUpdate, PostCreate, PostDelete, CommentUpdate, \
    MyPostList, MyCommentList, PostListByUser

app_name = 'home'
urlpatterns = [
    path('', PostList.as_view(), name='index'),
    path('<int:pk>/', PostDetail.as_view(), name='post_detail'),
    path('category/<str:slug>/', PostListByCategory.as_view(), name='post_list_category'),
    path('<int:pk>/update/', PostUpdate.as_view(), name='post_update'),
    path('create/', PostCreate.as_view(), name='post_create'),
    path('<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
    path('<int:pk>/comment_create/', views.comment_create, name='comment_create'),
    path('comment_update/<int:pk>/', CommentUpdate.as_view(), name='comment_update'),
    path('comment_delete/<int:pk>/', views.comment_delete, name='comment_delete'),
    path('my_post/', MyPostList.as_view(), name='my_post_list'),
    path('my_comment/', MyCommentList.as_view(), name='my_comment_list'),
    path('post_like/<int:pk>/', views.post_like, name="post_like"),
    path('user_post/<str:username>/', PostListByUser.as_view(), name='post_list_user'),
    path('about/', views.about, name='about_page'),
]

photo_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('allpictures/', include('allpictures.urls')),
    path('multi/', include('multiphoto.urls')),
    path('admin/', admin.site.urls),
    path('markdownx/', include('markdownx.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

allpictures/models.py
from django.db import models

# Create your models here.

allpictures/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render

# Create your views here.
from django.core.paginator import Paginator
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView

from home.models import Post


def picture_list(request):
    page = request.GET.get('page', 1)
    object_list = Post.objects.all().order_by('-created')
    paginator = Paginator(object_list, 24)
    objects = paginator.get_page(page)
    return render(request, 'allpictures/picture_list.html', context={"objects": objects})


def my_picture_list(request):
    current_user = request.user
    if current_user.is_authenticated:
        page = request.GET.get('page', 1)
        object_list = Post.objects.filter(author=current_user).order_by('-created')
        paginator = Paginator(object_list, 24)
        objects = paginator.get_page(page)
        return render(request, 'allpictures/my_picture_list.html', context={"objects": objects})
    else:
        return render(request, 'accounts/login.html')

allpictures/templates/allpictures/my_picture_list.html
{% extends 'home/base.html' %}
{% block content %}
<div class="container">
    <h4>My Photos</h4>
    <br />
    <br />
    <div class="row">
        {% if objects %}
        {% for p in objects %}
        <div class="col-6 col-md-3 col-lg-2" >
            <div>
                <a href="{% url 'home:post_detail' p.pk %}">
                    <img class="img-thumbnail" src={{ p.image.url }} width="100%" height="100%" alt="...">
                </a>
            </div>
        </div>
        <br />
        {% endfor %}
        {% else %}
        <h5 style="padding-left: 15px;">No Photo</h5>
        {% endif %}
    </div>
    <br />
    <br />
    <div>
        <ul class="pagination pagination-sm">
            {% if objects.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ objects.next_page_number }}">< Older</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">< Older</a>
            </li>
            {% endif %}
            {% if objects.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ objects.previous_page_number }}">Latest ></a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">Latest ></a>
            </li>
            {% endif %}
        </ul>
    </div>
</div>

{% endblock %}

allpictures/templates/allpictures/picture_list.html
{% extends 'home/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        {% if objects %}
        {% for p in objects %}
        <div class="col-6 col-md-3 col-lg-2" >
            <div>
                <a href="{% url 'home:post_detail' p.pk %}">
                    <img class="img-thumbnail" src={{ p.image.url }} width="100%" height="100%" alt="...">
                </a>
            </div>
        </div>
        <br />
        {% endfor %}
        {% else %}
    </div>
    <h1 class="container">No Post</h1>
    {% endif %}
</div>
<div>
    <ul class="pagination pagination-sm">
        {% if objects.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ objects.next_page_number }}">< Older</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#">< Older</a>
        </li>
        {% endif %}
        {% if objects.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ objects.previous_page_number }}">Latest ></a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#">Latest ></a>
        </li>
        {% endif %}
    </ul>
</div>

{% endblock %}
`