accounts/urls.py
from django.contrib import admin
from django.urls import path
from accounts import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

allpictures/urls.py
from django.contrib import admin
from django.urls import path
from allpictures import views

app_name = 'allpictures'
urlpatterns = [
    path('', views.picture_list, name='list'),
    path('my_picture', views.my_picture_list, name="my_picture_list"),
]

home/urls.py
from django.contrib import admin
from django.urls import path, include

from home import views
from home.views import PostList, PostDetail, PostListByCategory, PostUpdate, PostCreate, PostDelete, CommentUpdate, \
    MyPostList, MyCommentList, PostListByUser

app_name = 'home'
urlpatterns = [
    path('', PostList.as_view(), name='index'),
    path('<int:pk>/', PostDetail.as_view(), name='post_detail'),
    path('category/<str:slug>/', PostListByCategory.as_view(), name='post_list_category'),
    path('<int:pk>/update/', PostUpdate.as_view(), name='post_update'),
    path('create/', PostCreate.as_view(), name='post_create'),
    path('<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
    path('<int:pk>/comment_create/', views.comment_create, name='comment_create'),
    path('comment_update/<int:pk>/', CommentUpdate.as_view(), name='comment_update'),
    path('comment_delete/<int:pk>/', views.comment_delete, name='comment_delete'),
    path('my_post/', MyPostList.as_view(), name='my_post_list'),
    path('my_comment/', MyCommentList.as_view(), name='my_comment_list'),
    path('post_like/<int:pk>/', views.post_like, name="post_like"),
    path('user_post/<str:username>/', PostListByUser.as_view(), name='post_list_user'),
    path('about/', views.about, name='about_page'),
]

multiphoto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from multiphoto import views
from multiphoto.views import MultiList, MultiDetail, MultiDelete, CommentUpdate, MyMultiList, MyMultiCommentList, \
    MultiListByUser

app_name = 'multiphoto'
urlpatterns = [
    path('', MultiList.as_view(), name='index'),
    path('<int:pk>/', MultiDetail.as_view(), name='multi_detail'),
    path('<int:pk>/update/', views.multi_update, name='multi_update'),
    path('create/', views.multi_create, name='multi_create'),
    path('about/', views.multi_about, name='multi_about'),
    path('<int:pk>/delete/', MultiDelete.as_view(), name='multi_delete'),
    path('<int:pk>/comment_create/', views.comment_create, name='comment_create'),
    path('comment_update/<int:pk>/', CommentUpdate.as_view(), name='comment_update'),
    path('comment_delete/<int:pk>/', views.comment_delete, name='comment_delete'),
    path('my_post/', MyMultiList.as_view(), name='my_multi_list'),
    path('my_comment/', MyMultiCommentList.as_view(), name='my_multi_comment_list'),
    path('multi_like/<int:pk>/', views.multi_like, name="multi_like"),
    path('user_post/<str:username>/', MultiListByUser.as_view(), name='multi_list_user'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('allpictures/', include('allpictures.urls')),
    path('multi/', include('multiphoto.urls')),
    path('admin/', admin.site.urls),
    path('markdownx/', include('markdownx.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
from django.db.models import CASCADE
from django.db.models.signals import post_save
from django.dispatch import receiver
from markdown import markdown
from markdownx.models import MarkdownxField

from multiphoto.models import MultiPhoto


class Category(models.Model):
    name = models.CharField(max_length=20)
    slug = models.SlugField(unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return '/home/category/{}/'.format(self.slug)

    class Meta:
        verbose_name_plural = 'categories'


class Post(models.Model):
    title = models.CharField(max_length=15)
    category = models.ForeignKey(Category, on_delete=CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=CASCADE)
    image = models.ImageField(upload_to='home/%Y/%m/%d/', blank=False)
    content = models.TextField()
    like_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return '{}'.format(self.title)

    def get_absolute_url(self):
        return '/home/{}/'.format(self.pk)

    def get_post_update_url(self):
        return self.get_absolute_url() + 'update/'


class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    like_posts = models.ManyToManyField(Post, blank=True)

    def __int__(self):
        return self.user

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=CASCADE)
    author = models.ForeignKey(User, on_delete=CASCADE)
    text = MarkdownxField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def get_markdown_content(self):
        return markdown(self.text)

    def get_absolute_url(self):
        return self.post.get_absolute_url() + '#comment-id-{}'.format(self.pk)

    def __str__(self):
        return '{}'.format(self.text)

home/forms.py
from django import forms
from home.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

home/views.py
from django.shortcuts import render

# Create your views here.
from unicodedata import category

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from django.urls import reverse
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView

from home.forms import CommentForm
from home.models import Post, Category, Comment, Profile
from photo_site import settings


class PostList(ListView):
    model = Post
    paginate_by = 8

    def get_queryset(self):
        return Post.objects.order_by('-created')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_list'] = Category.objects.all()
        return context


class PostDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_list'] = Category.objects.all()
        context['comment_form'] = CommentForm()
        return context


class PostListByCategory(ListView):
    paginate_by = 8

    def get_queryset(self):
        slug = self.kwargs['slug']
        category = Category.objects.get(slug=slug)
        return category.post_set.order_by('-created')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_list'] = Category.objects.all()

        return context


class PostListByUser(ListView):
    paginate_by = 8

    def get_queryset(self):
        name = self.kwargs['username']
        user = User.objects.get(username=name)
        return user.post_set.order_by('-created')


class PostUpdate(LoginRequiredMixin, UpdateView):
    login_url = settings.LOGIN_URL
    model = Post
    fields = [
        'title', 'category', 'image', 'content'
    ]

    def get_object(self, queryset=None):
        post = super(PostUpdate, self).get_object()
        if post.author != self.request.user:
            raise PermissionError('Post 수정 권한이 없습니다.')
        return post


class PostCreate(LoginRequiredMixin, CreateView):
    login_url = settings.LOGIN_URL
    model = Post
    fields = ['title', 'category', 'image', 'content']

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated:
            form.instance.author = current_user
            return super(type(self), self).form_valid(form)
        else:
            return redirect('/')


class PostDelete(LoginRequiredMixin, DeleteView):
    login_url = settings.LOGIN_URL
    model = Post

    success_url = '/'

    def get_object(self, queryset=None):
        post = super(PostDelete, self).get_object()
        if post.author != self.request.user:
            raise PermissionError('Post 삭제 권한이 없습니다.')
        return post


def post_like(request, pk):
    post = Post.objects.get(pk=pk)

    if request.user.is_anonymous:
        return render(request, 'home/login_require.html')

    profile = Profile.objects.get(user=request.user)
    check_like_post = profile.like_posts.filter(pk=pk)

    if check_like_post.exists():
        profile.like_posts.remove(post)
        post.like_count -= 1
        post.save()
    else:
        profile.like_posts.add(post)
        post.like_count += 1
        post.save()

    return redirect('home:post_detail', pk)


def comment_create(request, pk):
    post = Post.objects.get(pk=pk)

    if request.method == 'POST':
        current_user = request.user
        if current_user.is_authenticated:
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
        return render(request, 'home/login_require.html')
    else:
        return redirect('/')


class CommentUpdate(UpdateView):
    model = Comment
    form_class = CommentForm

    def get_object(self, queryset=None):
        comment = super(CommentUpdate, self).get_object()
        if comment.author != self.request.user:
            raise PermissionError('Comment 수정 권한이 없습니다.')
        return comment


def comment_delete(request, pk):
    comment = Comment.objects.get(pk=pk)
    post = comment.post
    if request.user == comment.author:
        comment.delete()
        return redirect(post.get_absolute_url()+'#comment-list')
    else:
        return redirect('/')


class MyPostList(LoginRequiredMixin, ListView):
    login_url = settings.LOGIN_URL
    model = Post
    paginate_by = 8

    def get_queryset(self):
        object_list = Post.objects.filter(author=self.request.user)
        return object_list.order_by('-created')


class MyCommentList(LoginRequiredMixin, ListView):
    login_url = settings.LOGIN_URL
    model = Comment
    paginate_by = 20

    def get_queryset(self):
        object_list = Comment.objects.filter(author=self.request.user)
        return object_list.order_by('-modified_at')


def about(request):
    return render(request, 'home/about.html')

multiphoto/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from django.db import transaction
from django.views.generic import ListView, DetailView, DeleteView, UpdateView

from multiphoto.forms import MultiForm, ImageFormSet, MultiCommentForm
from multiphoto.models import MultiPhoto, MultiComment


class MultiList(ListView):
    model = MultiPhoto
    paginate_by = 8

    def get_queryset(self):
        return MultiPhoto.objects.order_by('-created')


class MultiDetail(DetailView):
    model = MultiPhoto

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['multicomment_form'] = MultiCommentForm()
        return context


@login_required
def multi_create(request):
    if request.method == 'POST':
        multi_form = MultiForm(request.POST)
        image_formset = ImageFormSet(request.POST, request.FILES)
        if multi_form.is_valid() and image_formset.is_valid():
            post = multi_form.save(commit=False)
            post.author = request.user

            with transaction.atomic():
                post.save()
                image_formset.instance = post
                image_formset.save()
                return redirect('multiphoto:index')
    else:
        multi_form = MultiForm()
        image_formset = ImageFormSet()

    return render(request, 'multiphoto/multi_create.html', {
        'multi_form': multi_form,
        'image_formset': image_formset,
    })


@login_required
def multi_update(request, pk):
    post = get_object_or_404(MultiPhoto, pk=pk)
    if post.author != request.user:
        return redirect('multiphoto:index')
    else:
        if request.method == 'POST':
            multi_form = MultiForm(request.POST, instance=post)
            image_formset = ImageFormSet(request.POST, request.FILES, instance=post)
            if multi_form.is_valid() and image_formset.is_valid():
                multi_form.save()
                image_formset.save()

                return redirect('multiphoto:multi_detail', pk)
        else:
            multi_form = MultiForm(instance=post)
            image_formset = ImageFormSet(instance=post)
        return render(request, 'multiphoto/multi_create.html', {
            'multi_form': multi_form,
            'image_formset': image_formset,
        })


class MultiDelete(LoginRequiredMixin, DeleteView):
    login_url = settings.LOGIN_URL
    model = MultiPhoto

    success_url = '/multi'

    def get_object(self, queryset=None):
        post = super(MultiDelete, self).get_object()
        if post.author != self.request.user:
            raise PermissionError('Post 삭제 권한이 없습니다.')
        return post


class MyMultiList(LoginRequiredMixin, ListView):
    login_url = settings.LOGIN_URL
    model = MultiPhoto
    paginate_by = 8

    def get_queryset(self):
        object_list = MultiPhoto.objects.filter(author=self.request.user)
        return object_list.order_by('-created')


class MultiListByUser(ListView):
    paginate_by = 8

    def get_queryset(self):
        name = self.kwargs['username']
        user = User.objects.get(username=name)
        return user.multiphoto_set.order_by('-created')


def comment_create(request, pk):
    post = MultiPhoto.objects.get(pk=pk)
    form = MultiCommentForm(request.POST)
    if request.method == 'POST':
        current_user = request.user
        if current_user.is_authenticated:
            if form.is_valid():
                comment = form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
        return render(request, 'home/login_require.html')
    else:
        return redirect(request, 'multicomment_form.html', {'form': form, })


class CommentUpdate(UpdateView):
    model = MultiComment
    form_class = MultiCommentForm

    def get_object(self, queryset=None):
        comment = super(CommentUpdate, self).get_object()
        if comment.author != self.request.user:
            raise PermissionError('Comment 수정 권한이 없습니다.')
        return comment


def comment_delete(request, pk):
    comment = MultiComment.objects.get(pk=pk)
    post = comment.post
    if request.user == comment.author:
        comment.delete()
        return redirect(post.get_absolute_url()+'#comment-list')
    else:
        return redirect('/multi')


class MyMultiCommentList(LoginRequiredMixin, ListView):
    login_url = settings.LOGIN_URL
    model = MultiComment
    paginate_by = 20

    def get_queryset(self):
        object_list = MultiComment.objects.filter(author=self.request.user)
        return object_list.order_by('-modified_at')


def multi_like(request, pk):
    post = get_object_or_404(MultiPhoto, pk=pk)

    if request.user.is_anonymous:
        return render(request, 'home/login_require.html')

    if request.user in post.lover.all():
        post.lover.remove(request.user)
    else:
        post.lover.add(request.user)

    return redirect('multiphoto:multi_detail', pk)


def multi_about(request):
    return render(request, 'multiphoto/about.html')

home/templates/home/about.html
{% extends 'home/base.html' %}
{% block content %}
<div class="container" style="padding: 20px; ">
    <h5> Share your today's best moment with a photo!</h5>
    <p>That maybe Landscape when you went for a stroll, or some foods you ate for lunch, and a cat you discovered when you went to work. </p>
    <p>Then, you can feel special in your daily routine!</p>
    <button type="button" class="btn btn-outline-secondary btn-sm" onClick="location.href='{% url 'home:post_create' %}'">Write</button>
    <button type="button" class="btn btn-outline-secondary btn-sm" onClick="location.href='{% url 'accounts:login' %}'">Login</button>

    <hr />
    <p>opening date: 2020-05-15</p>

</div>
{% endblock %}

home/templates/home/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="Keywords" content="사진, 일상, 뻘글, 심심, 사진사이트">
    <meta name="Description" content="사진, 일상, 심심, 사진사이트">
    <meta http-equiv="Subject" content="사진공유">
    <title>사진첩</title>
    <link rel="stylesheet" href="{% static 'home/css/bootstrap.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'home/css/custom.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/reset.css' %}">
    <link rel="shortcut icon" href="{% static 'home/favicon/favicon.ico' %}">
    <link rel="icon" href="{% static 'home/favicon/favicon.ico' %}">
    <script src="https://kit.fontawesome.com/b962c21d10.js" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top" style="padding: 0.5rem ">
    <div>
        <a class="navbar-brand" href="/">사진첩</a>
        <a href="{% url 'allpictures:list' %}">모아보기<i class="fas fa-image"></i></a>
        <a href="{% url 'multiphoto:index' %}" class="text-success" style="float: right;">Multi</a>
        <div class="collapse navbar-collapse container" id="navbarColor03">
            <div class="btn-group">
                <a href="{% url 'home:post_create' %}">Write<i class="fas fa-pen"></i></a>
            </div>
            <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    Category <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">All<span class="sr-only">(current)</span></a>
                    </li>
                    {% for category in category_list %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:post_list_category' category.slug %}">{{ category.name }}({{ category.post_set.count }})</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <!-- Single button -->
            <div class="btn-group">
                {% if user.is_authenticated %}
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <i class="fas fa-heart"></i>  My<span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'home:my_post_list' %}">My Posts</a></li>
                    <li><a href="{% url 'allpictures:my_picture_list' %}">My Photos</a></li>
                    <li><a href="{% url 'home:my_comment_list' %}">My Comments </a></li>
                    <li><a href="/accounts/logout/">Logout</a></li>
                </ul>
                {% else %}
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    Menu <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'home:about_page' %}">About</a></li>
                    <li><a href="/accounts/login/">Login</a></li>
                    <li><a href="/accounts/signup/">Sign up</a></li>
                </ul>
                {% endif %}
            </div>
        </div>

    </div>

</nav>
{% block content %}{% endblock %}

<script src="{% static 'home/js/jquery.min.js' %}"></script>
<script src="{% static 'home/js/popper.min.js' %}"></script>
<script src="{% static 'home/js/bootstrap.min.js' %}"></script>
<script src="{% static 'home/js/custom.js' %}"></script>


</body>
</html>

home/templates/home/comment_form.html
{% extends 'home/base.html' %}

{% block content %}
<h3>Modify Comment: </h3>
<hr/>
<form method="post">{% csrf_token %}

    <table>
        {{ form.as_table }}
    </table>
    <button type="submit" class="btn btn-primary btn-sm">Submit</button>
</form>

{{ form.media }}
{% endblock %}

home/templates/home/comment_list.html
{% extends 'home/base.html' %}
{% block content %}
<div class="container">
    <h4>My comments</h4>
    <br />
    <br />
    {% if object_list %}
    {% for c in object_list %}
    <span class="badge badge-light">{{ c.modified_at }}</span>/<span class="badge badge-pill badge-primary"><a href="{% url 'home:post_detail' c.post.pk %}" style="color: white; ">{{ c.post.title }}</a></span>
    <p>{{ c.text | truncatewords:30  }}</p>
    <br />
    {% endfor %}
    {% else %}
    <h5>No Comment</h5>
    {% endif %}
    <br />
    <br />
    {% if is_paginated %}
    <div>
        <ul class="pagination pagination-sm">
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">< Older</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">< Older</a>
            </li>
            {% endif %}
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Latest ></a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">Latest ></a>
            </li>
            {% endif %}
        </ul>
    </div>
    {% endif %}

</div>

{% endblock %}

home/templates/home/login_require.html
{% extends 'home/base.html' %}
{% block content %}
<div align="center">
    <p>Login is required</p>
    <button type="button" class="btn btn-outline-secondary btn-sm" onClick="location.href='/'">Home</button>
    <button type="button" class="btn btn-outline-secondary btn-sm" onClick="location.href='{% url 'accounts:login' %}'">Login</button>
</div>
{% endblock %}

home/templates/home/permissionError.html
{% extends 'home/base.html' %}
{% block contents %}
<p>권한이 없습니다</p>
{% endblock %}

home/templates/home/post_confirm_delete.html
{% extends 'home/base.html' %}
{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <button type="submit" class="btn btn-link">Delete</button>
</form>
{% endblock %}

home/templates/home/post_detail.html
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="thumbnail-detail container" xmlns:blog="http://www.w3.org/1999/xhtml" xmlns:blog="http://www.w3.org/1999/xhtml">
    <h3>{{ object.title }}</h3>
    <span class="badge badge-success"><a href="{% url 'home:post_list_user' object.author.username %}" style="color: white; ">{{ object.author }}</a></span></span>
    <span class="badge badge-secondary">{{ object.created }}</span>
    <span class="badge badge-secondary">{{ object.category }}</span>
    {% if request.user == object.author %}
    <button type="button" class="btn btn-outline-secondary btn-sm" onClick="location.href='{{ object.get_post_update_url }}'">Edit</button>
    <button type="button" class="btn btn-outline-secondary btn-sm" onClick="location.href='{% url 'home:post_delete' object.pk %}'">Delete</button>
    {% endif %}
    <div>
    <img class="img-thumbnail" style="padding: 10px" src="{{ object.image.url }}" style="max-width:100%; height: auto;" alt="...">
    </div>
    <div style="padding-top: 20px; " />
    <div class="caption">
        <p>{{ object.content }}</p>
        <br />
        <button type="button" class="btn btn-outline-secondary btn-sm" onclick="location.href='{% url 'home:post_like' object.pk %}'">
            <i class="fas fa-splotch"></i><span class="badge badge-secondary">like ({{ object.like_count }})</span></button>
    </div>
</div>
<br />
<br />
<hr />
<div class="container">
    <form method="POST" action="{% url 'home:comment_create' object.pk %}">{% csrf_token %}
        <div class="form-group">
            <label>Comments</label>
            {{ comment_form | crispy }}
            <button type="submit" class="btn btn-outline-primary btn-sm">Submit</button>
        </div>
    </form>
</div>
<br />
<br />
<div class="container">
    <div id="comment-list" style="border: 1px solid #A4A4A4; margin-bottom: 20px; ">
        {% for comment in object.comment_set.all %}
        <div class="media mb-4" id="comment-id-{{ comment.pk }}">
            <div class="media-body container">
                <span class="badge badge-success"><a href="{% url 'home:post_list_user' comment.author %}" style="color: white;">{{ comment.author }}</a></span><span class="badge badge-secondary">{{ comment.modified_at }}</span>
                <p>{{ comment.get_markdown_content | safe }}</p>
                {% if request.user == comment.author %}
                <span class="badge badge-pill badge-primary"><a style="color: white;" href="{% url 'home:comment_update' comment.pk %}">Modify</a></span>
                <span class="badge badge-pill badge-primary"><a style="color: white;" href="{% url 'home:comment_delete' comment.pk %}">Delete</a></span>
                {% endif %}
            </div>

        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

home/templates/home/post_form.html
{% extends 'home/base.html' %}
{% block title %}{{ object.title }} - Blog{% endblock %}
{% block content %}
<br />
<div class="container">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary btn-sm">Update</button>
</form>
<br />
<a href="{% url 'multiphoto:multi_create' %}" style="color: blue;">Do you want to upload photos more than 1? ></a>
</div>
{% endblock %}

home/templates/home/post_list.html
{% extends 'home/base.html' %}
{% block content %}
<div class="row" style="width: 100%">
    {% if object_list %}
    {% for p in object_list %}
    <div class="list col-md-4 col-lg-3">
        <span class="badge badge-secondary">{{ p.created }}</span>
        <div class="img-thumbnail" style="padding-left:8px; padding-right:8px;">
            <a href="{% url 'home:post_detail' p.pk %}">
                <div>
                <img src={{ p.image.url }} style="max-width: 100%; height:auto; " alt="...">
                </div>
            </a>
            <div class="caption">
                <h4><a href="{% url 'home:post_detail' p.pk %}" style="text-decoration: none;">{{ p.title }}</a></h4> {% if p.comment_set.count >= 1 %}
                <span class="badge badge-pill badge-light float-right"><p>({{ p.comment_set.count }})</p></span>
                {% endif %}
                {% if p.like_count >= 1 %}
                <p><i class="fas fa-splotch primary float-right">({{ p.like_count }})</i></p>
                {% endif %}
                <span class="badge badge-pill badge-secondary">author:</span>
                <span class="badge badge-success"><a href="{% url 'home:post_list_user' p.author.username %}" style="color: white; ">{{ p.author }}</a></span>
                <p>{{ p.content | truncatewords:20 }}</p>
                <a href="{% url 'home:post_detail' p.pk %}"><span class="label label-success">detail<i class="fas fa-angle-right"></i></span></a>
            </div>
        </div>
        <br />
    </div>
    {% endfor %}
    {% else %}
    <h1 class="container">No Post</h1>
    {% endif %}
</div>
{% if is_paginated %}
<div >
    <ul class="pagination pagination-sm">
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">< Older</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#">< Older</a>
        </li>
        {% endif %}
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Latest ></a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#">Latest ></a>
        </li>
        {% endif %}
    </ul>
</div>
{% endif %}

{% endblock %}